# Generated by Django 6.0.2 on 2026-02-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuxsolToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auxsol Token',
                'verbose_name_plural': 'Auxsol Tokens',
            },
        ),
        migrations.CreateModel(
            name='InverterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_power', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('daily_yield', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_yield', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
