# Generated by Django 6.0.2 on 2026-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxsol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxsoltoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Auxsol Token', 'verbose_name_plural': 'Auxsol Tokens'},
        ),
        migrations.AlterModelOptions(
            name='inverterdata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Inverter Data', 'verbose_name_plural': 'Inverter Data'},
        ),
        migrations.AlterField(
            model_name='auxsoltoken',
            name='access_token',
            field=models.CharField(help_text='Auxsol API access token', max_length=500),
        ),
        migrations.AlterField(
            model_name='auxsoltoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Token yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='auxsoltoken',
            name='expires_at',
            field=models.DateTimeField(help_text='Token muddati tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='current_power',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Joriy quvvat (kW)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='daily_yield',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Kunlik hosil (kWh)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text="Ma'lumot qayd etilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='total_yield',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Jami hosil (kWh)', max_digits=15),
        ),
        migrations.AddIndex(
            model_name='auxsoltoken',
            index=models.Index(fields=['-created_at'], name='auxsol_app__created_958c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='inverterdata',
            index=models.Index(fields=['-timestamp'], name='auxsol_app__timesta_bbac88_idx'),
        ),
        migrations.AddIndex(
            model_name='inverterdata',
            index=models.Index(fields=['current_power'], name='auxsol_app__current_8d3388_idx'),
        ),
    ]
