# Generated by Django 6.0.2 on 2026-02-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxsol_app', '0002_alter_auxsoltoken_options_alter_inverterdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverterdata',
            name='co2_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='daily_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='monthly_yield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='trees_planted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='current_power',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='daily_yield',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='total_yield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
