"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""
import dj_database_url
import os
from dotenv import load_dotenv
from pathlib import Path
from celery.schedules import crontab

# Load .env file
load_dotenv()

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ BUGFIX: SECRET_KEY
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key-for-development')

# ✅ BUGFIX: DEBUG = True (DEVELOPMENT UCHUN)
DEBUG = True  # Development'da True qiling, Production'da False

# ✅ BUGFIX: ALLOWED_HOSTS
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'fedora',
    '0.0.0.0',
    '*'  # Development uchun wildcard (Production'da specific hosts qiling!)
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auxsol_app',
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ✅ RENDER UCHUN DATABASE SOZLAMASI
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Tashkent'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ✅ RENDER UCHUN REDIS SOZLAMASI
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# ✅ BUGFIX: Celery sozlamalar
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minut

# ============= BEAT SCHEDULER =============

# ✅ BUGFIX: CELERY_BEAT_SCHEDULE
CELERY_BEAT_SCHEDULE = {
    'sync-solar-every-5-min': {
        'task': 'auxsol_app.tasks.sync_solar_data',
        'schedule': crontab(minute='*/5'),  # Har 5 minutda
        'options': {'expires': 600}
    },
    'cleanup-old-data-daily': {
        'task': 'auxsol_app.tasks.cleanup_old_data',
        'schedule': crontab(hour=2, minute=0),  # Har kun 02:00 AM
        'options': {'expires': 3600}
    },
}

# ============= LOGGING =============

# ✅ BUGFIX: Logging sozlamasi
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {funcName}:{lineno} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'solar_monitor.log',
            'formatter': 'verbose',
            'level': 'INFO',
        },
    },
    'loggers': {
        'auxsol_app': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    }
}

# ============= DRF SPECTACULAR =============

# ✅ BUGFIX: Swagger sozlamasi
SPECTACULAR_SETTINGS = {
    'TITLE': 'Solis Monitor API',
    'DESCRIPTION': 'Quyosh panellari ma\'lumotlarini kuzatish API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums'
    ],
    'SWAGGER_UI_SETTINGS': {
        'defaultModelExpandDepth': 3,
        'defaultModelRendering': 'example',
        'displayRequestDuration': True,
    },
}